// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abtyjihtkwxlaqskopha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFidHlqaWh0a3d4bGFxc2tvcGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NjI4MDgsImV4cCI6MjA3NjUzODgwOH0.TlwCQcZiu9lMtegq2M171-UJftjfE4Z3stF-AA4Zg_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});